### ISSUE TITLE
dropdowns for Polymer 1.0?

### ISSUE THREAD

**Issue by dough10** [Polymer/paper-dropdown-menu#63] opened 2015-06-06 12:06 UTC
any plans to update the dropdown elements to polymer 1.0?

**Comment by yawenzhongyuan** [comment] 2015-06-08 09:09
want it,too!

**Comment by grokys** [comment] 2015-06-09 14:06
+1

**Comment by fredpedro** [comment] 2015-06-10 12:56
When you view the source of polymer-project.org, it is very apparent that they are using paper-dropdown-menu. But when I try to use it on my Polymer version 1.0 project, it just doesn't work. Perhaps there is a replacement for this element in version 1.

**Comment by SmokyBob** [comment] 2015-06-10 20:24
`paper-dropdown-menu` is being upgraded to 1.0
You can follow `paper-elements` roadmap [here](https://github.com/PolymerElements/paper-elements)

I guess the work is currently in a private branch/repo and will be published under the PolymerElements when ready (patiently waiting for it too to upgrade a couple of apps)

**Comment by notthetup** [comment] 2015-06-12 07:23
:+1:

**Comment by tonytonyjan** [comment] 2015-06-27 08:50
:+1:

**Comment by richardhundt** [comment] 2015-07-03 20:44
:+1:

**Comment by lcasartelli** [comment] 2015-07-06 13:00
+1

**Comment by notwaldorf** [comment] 2015-07-07 15:21
Closing this, as it's technically a duplicate of https://github.com/PolymerElements/paper-elements/issues/17. This is an element we're currently working on, and it should be available soon! :)

**Closed by notwaldorf** 2015-07-07 15:21 UTC

**Comment by Sinjins** [comment] 2015-07-29 01:19
+1

**Comment by zenorocha** [comment] 2015-08-06 22:36
FYI this element has been released couple hours ago: https://github.com/PolymerElements/paper-dropdown-menu/releases
